### PR TITLE
Calendar sync: Calendar manipulation error handling, fixes #324

### LINKED ISSUE #324: CalendarSync exception
The following exception was reported via Google:

````
java.lang.RuntimeException: Unable to create application nl.mpcjanssen.simpletask.TodoApplication: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars?caller_is_syncadapter=true&account_name=Simpletask%20Calendar&account_type=LOCAL
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4596)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
	at android.app.ActivityThread.handleBindApplication(<Xposed>)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars?caller_is_syncadapter=true&account_name=Simpletask%20Calendar&account_type=LOCAL
	at android.content.ContentResolver.insert(ContentResolver.java:1203)
	at nl.mpcjanssen.simpletask.CalendarSync.addCalendar(CalendarSync.java:118)
	at nl.mpcjanssen.simpletask.CalendarSync.setSyncType(CalendarSync.java:242)
	at nl.mpcjanssen.simpletask.CalendarSync.<init>(CalendarSync.java:264)
	at nl.mpcjanssen.simpletask.TodoApplication.onCreate(TodoApplication.java:113)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
	... 13 more
````

### PR DESCRIPTION
**Pull request by vojtechkral**
Fix for #324 , insofar as not crashing and displaying an error message instead can be considered a fix...

@twckr mind checking my german for me one more time? :)

### CODE REVIEW

**Comment by twckr** [comment]
@vojtechkral 

`Fehler: Kann Kalender nicht hinzufügen`

**Comment by vojtechkral** [comment]
Ok, I'll update...

**Comment by mpcjanssen** [comment]
Not crashing is fix enough. One question why do you use magic return codes (-1) instead of just propagating the exception?

**Comment by vojtechkral** [comment]
Umm, not sure, I the -1 began as a "there's no calendar" information, but I started using it for errors too. I'll fix...

**Comment by mpcjanssen** [comment]
No big rush.

**Pull request merged**
