### PR TITLE
Better settings arrangement and phrasing

### PR DESCRIPTION
**Pull request by smichel17**
See #421 (and now a little bit more)

### CODE REVIEW

**Comment by smichel17** [comment]
The second commit requires additional changes before it can be pushed to f-droid/play store!

Under "User Interface" and "configuration" there are now two tasks which become disabled based on the state of another task (the one immediately above). The tasks that get disabled should revert to their initial state (both functionality *and* display) while they are disabled, then return to their former state when enabled again.

**Comment by mpcjanssen** [comment]
I don't understand exactly what you mean here. Can you explain? I don't see any dependent settings.

**Comment by smichel17** [comment]
I meant disabled in the UI. added an android:dependency.

If "show confirmation dialogues" is checked, the user will not be able to turn on "automatically archive upon completion". This is the proper behavior because automatically archive upon completion bypasses the confirmation dialogue that would normally show when you try to archive all, and the user should be warned of this. 

However, currently in this commit if you turn off confirmation dialogues, enable automatic archive upon completion, and then enable confirmation dialogues again, automatic archive grays out but stays enabled.

The correct functionality would be, when confirmation dialogues are enabled, auto archive grays out and is set to disabled (including both functionality _and appearance of the grayed out setting._ When confirmation dialogues are disabled,  auto archive should remember its former state (in this case, enabled).

Same thing goes for the "background tag" and "Text to append" settings. If Background Tag is turned off, "Text to append" should be an empty string, and it should return to its former value when Background Tag is enabled again. 

Actually, it would be nice if an empty string caused the secondary text to read "none". But that can be done in a separate issue.

**Comment by smichel17** [comment]
Is 2 merge commits ok or would you prefer I rebase?

**Comment by smichel17** [comment]
If it would be helpful, I could separate this into two MRs, one which can be merged immediately.

**Comment by smichel17** [comment]
Any changes to settings make this really hard to merge, like right now. I'm going to re-do this as two separate MRs, one of which can be merge immediately, and the other of which is much smaller and won't conflict with literally every other change to the settings.

**Pull request closed without merging**
