### PR TITLE
move lua config buttons to the actionBar

### PR DESCRIPTION
**Pull request by smichel17**
Moves the buttons at the bottom of the lua config into the app bar.

~~Do a reset if you pull this, because I will be rebasing.~~ Done.

~~I added `res/menu/lua_config.xml` and then added icons to what I think is the correct drawable folders. Yet I am getting a build error, `Error:(12, 23) No resource found that matches the given name (at 'icon' with value '@drawable/ic_play.png').`~~

### CODE REVIEW

**Comment by mpcjanssen** [comment]
Drop the .png in the @drawable

**Comment by smichel17** [comment]
@mpcjanssen ready to merge.

Worth noting this is my first time working in kotlin and I'm learning by copy-pasting bits of your code, so code review is relatively important (although it's a small change).

**Comment by mpcjanssen** [comment]
@smichel17 can this be merged?

**Comment by smichel17** [comment]
I believe so. I'm going to look at it again (to see what it looks like if help and share go in the overflow menu and run is shown WithText, but if U decide that's better I can always just make another PR.

**Comment by mpcjanssen** [comment]
Thanks

**Comment by smichel17** [comment]
(WithText doesn't look as nice)

**Pull request merged**
