### PR TITLE
prepend date to ok google messages

### PR DESCRIPTION
**Pull request by y2kbugger**
I guess this is a pretty naive change, and I couldn't test it in the emulator in Android studio because of no microphone. This is my first attempt at any android development.

### CODE REVIEW

**Comment by mpcjanssen** [comment]
Looks good, will merge after I have a chance to test (I am on holidays at the moment)

**Comment by mpcjanssen** [comment]
Test builds with this commit merged can be tried from http://mpcjanssen.nl/files/simpletask/y2kbugger-issue186/2015-01-16-dfe339a/

**Comment by y2kbugger** [comment]
Tested working for both manual add and voice add, obeying the setting both enabled and disable.

**Comment by mpcjanssen** [comment]
Merged, thanks for this.

**Pull request merged**
