### PR TITLE
Revert "Spanish translation for "Todo.txt extensions" doc file"

### PR DESCRIPTION
**Pull request by ddisanti**
Reverts mpcjanssen/simpletask-android#1046

### CODE REVIEW

**Comment by ddisanti** [comment]
@mpcjanssen sorry for the inconvenience. Can you tell me what happened? I'm doing PR directly from the Github site directly.

**Comment by ddisanti** [comment]
I sync from your repo to my fork and then make the PR based on the resulting diffs.

**Comment by mpcjanssen** [comment]
This was my mistake I'll close this one. Can you create a new pull request?

**Comment by mpcjanssen** [comment]
@ddisanti I really screwed up with doing the force push. Seems the only way to really fix this is for you to create a new fork and from that create the new pull request. Sorry for the hassle

**Comment by ddisanti** [comment]
No problem.  It's nothing compared to the hard work you put into ST.
Thanks to you!

**Pull request closed without merging**
