### PR TITLE
Add ability to pin tasks as notifications

### PR DESCRIPTION
**Pull request by camgraff**
Partially addresses https://github.com/mpcjanssen/simpletask-android/issues/964.

Adds an additional button to the task bar that allows pinning tasks as notifications. A task can be marked complete from the notification. When a task is edited/completed inside the app the notification is also updated accordingly.

simpletask-notification

### CODE REVIEW

**Comment by mpcjanssen** [comment]
Thanks very nice.

**Comment by smichel17** [comment]
Agreed it's very nice, but one nitpick: this will make the bottom bar overflow on small-screen devices. See also #1154, where I mentioned the same concern.

Conceptually, I think it would be best to keep the bottom bar for actions that directly change the task text. There's some options for what to do for everything else.

- The least effort is to just move them to the top bar, in an overflow menu if needed.
- The best solution, imo, is to change the FAB so that it expands into a menu of some sort.
- A compromise between effort and functionality is to make a row of small-size FABs floating above the bottom bar.

@camgraff Would you be up for doing one of those as a follow up? If so, let me know which option you're interested in and I can share some more detailed thoughts

**Comment by camgraff** [comment]
@smichel17 yeah these seem like good ideas. 

> Conceptually, I think it would be best to keep the bottom bar for actions that directly change the task text.

Agreed. I saw in #1154 you mentioned moving the "edit" button. Would you put that in the FAB menu as well?

> The least effort is to just move them to the top bar, in an overflow menu if needed.

I like that this keeps the action one tap away where as a FAB menu would involve an extra tap.

> A compromise between effort and functionality is to make a row of small-size FABs floating above the bottom bar.

Not thrilled about this one, multiple FABs feels clunky and they'd start to block text at the bottom of the list.

**Comment by smichel17** [comment]
Sorry for taking so long to get back to this, I got busy and it slipped off my rader. I opened #1182 to track this (and summarized all my current thoughts on the issue) so we're not just discussing in a merged PR.

**Pull request merged**
