### PR TITLE
Refactor selection menus, update all icons

### PR DESCRIPTION
**Pull request by smichel17**

### CODE REVIEW

**Comment by mpcjanssen** [comment]
@smichel17 very nice. Thank you. Will check how it looks on a smaller device and then merge.

**Comment by mpcjanssen** [comment]
@smichel17 still some issues with the actionbar selection menu items, they need to be moved to the onOptionsItemSelected. Will fix this and then merge

**Comment by mpcjanssen** [comment]
Also hamburger menu should change to up arrow when selection is active

**Comment by smichel17** [comment]
I tried making some of them ifRoom instead of always, but then they never display for some reason. If you can figure out how to make ifRoom behave properly, that would be awesome.

I didn't test on any devices besides an emulated Nexus 5x. We should definitely push this to beta before everyone gets it.

**Comment by smichel17** [comment]
I might not have time tonight but at some point I'll fire up an emulator running kitkat, too.

**Comment by mpcjanssen** [comment]
@smichel17 the ifRoom thing is a broken mess (was the reason that the old selection menu was so small) and yes I will put this in beta first.

**Pull request merged**
