### PR TITLE
Calendar sync: Don't prefix event titles any more

### PR DESCRIPTION
**Pull request by vojtechkral**
It makes calendar view unnecessarily messy, I don't know why I did this in the first place...

prefixed tasks

### CODE REVIEW

**Comment by vojtechkral** [comment]
@mpcjanssen Do you keep track of who translates strings? It might be good idea to ping them...

**Comment by mpcjanssen** [comment]
No not really. I just receive occasional pull requests. Thats the thing with translations, it looks really nice but it's challenging to maintain.

**Comment by vojtechkral** [comment]
Yeah. I recall @twckr did german translation, which I've filled in this time, but my German is a little rusty, so I'm not sure it's ok. Then there's @onekk (Italian) and @Martin-Laclaustra (Spanish) - would you guys be so kind as to have a look at the strings I modified? I have no idea about Korean...

**Comment by durcheinandr** [comment]
In the strings `Fälligkeitsdatum Erinnerung, automatisch erstellt von Simpletask` and
`Anfangsdatum Erinnerung, automatisch erstellt von Simpletask` should the word `Erinnerung` at first place.

`Erinnerung Fälligkeitsdatum, automatisch erstellt von Simpletask` and
`Erinnerung Anfangsdatum, automatisch erstellt von Simpletask` looks better for native german speakers.

But maybe @twckr has a better idea.

**Comment by twckr** [comment]
My recommendation would be

`Fälligkeitsdatum der Erinnerung (automatisch erstellt von Simpletask)` and
`Anfangsdatum der Erinnerung (automatisch erstellt von Simpletask)`

How about that @durcheinandr

**Comment by durcheinandr** [comment]
@twckr perfect

**Comment by vojtechkral** [comment]
@twckr Maybe it's because of my German not being very good, but this looks weird to me. It's the 2nd case isn't it? To me looks as if it were `Fälligkeitsdatum (of the) Erinnerung`, but it should be the other way around, that is `Erinnerung dem Fälligkeitsdatum` ... ?

**Comment by twckr** [comment]
@vojtechkral Your German seems to be quite good. You are perfectly right. Are you using the new strings as descriptions for the events?

`Erinnerung an das Fälligkeitsdatum`
`Erinnerung an der Anfangsdatum`

..would be correct. I will commit these.

**Comment by vojtechkral** [comment]
> Are you using the new strings as descriptions for the events?

Yup.

> I will commit these.

Great, thanks!

**Comment by mpcjanssen** [comment]
Will merge it when it arrives. Getting a community here, cool :)

**Comment by mpcjanssen** [comment]
I am slow. It was already there. Merged German updates.

**Comment by durcheinandr** [comment]
@mpcjanssen I think most people here have the same goals (with their data). Sadly a Github-repository is not the right place to discuss offtopic things like google-free smartphones, cloud-free data, doing stuff with txt-files (like todo.txt) and other related stuff. Neither is the gitter.im repository channel.

So if anyone knows a community (forum, irc-channel, blog-planet, etc.) with focus on these topics - please share

**Comment by vojtechkral** [comment]
As far as I can tell, gitter channel seems fine for such talks...

**Comment by mpcjanssen** [comment]
I would definitely welcome such discussion on gitter.

**Pull request merged**
