### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by Martin-Laclaustra**
Dear Mark,

I was a bit surprised that you already had uploaded the strings.xml. Anyway, I translated the docs as well. To enable this I modified some of the code (java) files. I tried to stick to minimal modifications. A more general approach was possible but you are the one able to decide which is the best strategy for i8n.
For now: In strings.xml, a string can indicate which help file should be loaded. As the index help and the addtask help were "hardcoded" as constants, I had to superseed those with entries in strings.xml. The more general approach could be to use just the file name in the constants (without extension) and allow the language-specific tail to be added.
I hope that you like the solution. Let me know your thoughts.
Best,
Martin

### CODE REVIEW

**Comment by mpcjanssen** [comment]
The upload of the strings was a mistake, it got accidentally include with an unrelated commit, sorry about that. I will look into the language specific help files. Maybe there is also a language specific asset directory.

**Comment by mpcjanssen** [comment]
I like using a translated string to get to the right help files. I will use that approach with a small twist. I will only add the one string help_locale which is you help_translation string.

**Comment by mpcjanssen** [comment]
Merged your commit with master with proper owner/authorship. Thanks very much for this. Could you check a build from master for any problems with the Spanish locale?

**Comment by Martin-Laclaustra** [comment]
Will do. I will need some days again. Patience.

Thanks to you for your work.

Best,
Martin

2015-06-07 12:57 GMT+02:00 Mark Janssen <notifications@github.com>:

**Pull request merged**
