### PR TITLE
Calendar sync: If calendar exists, only display a warning

### PR DESCRIPTION
**Pull request by vojtechkral**

### CODE REVIEW

**Comment by vojtechkral** [comment]
Hope I'm not too late for the new version? :-/

**Comment by mpcjanssen** [comment]
5.3.0 is already released, but I will merge this and update the release soon. I also have some scripting updates.

**Comment by mpcjanssen** [comment]
one remark, there is already a showtoast method in the Util class. So I will change your code to use that

**Comment by vojtechkral** [comment]
Hang on, there's a but in this code :-/ I'll update...

**Comment by mpcjanssen** [comment]
What's the bug? I already merged this. Can you create a new pull request for any updates?

**Comment by vojtechkral** [comment]
I forgot a return statement. Ok, new PR...

**Comment by vojtechkral** [comment]
Which branch should I create a PR against?

**Comment by mpcjanssen** [comment]
Always against master

**Pull request closed without merging**
