### PR TITLE
Add themes to Help pages.

### PR DESCRIPTION
**Pull request by Geehu**
This is a step towards fixing: https://github.com/mpcjanssen/simpletask-android/issues/569

The meaning of isDarkTheme has been changed from meaning 'dark or black' to mean exclusively 'dark'.

The only difference between light.css and black.css are five colors. (Background, foreground, link, header, code)

The only difference between black.css and dark.css is a single color. (The background).

I don't know if the colors will look good or be usable in all circumstances. If different colors are wanted, or if you want this implemented differently, please let me know.

### CODE REVIEW

**Comment by smichel17** [comment]
> The only difference between light.css and black.css are five colors. (Background, foreground, link, header, code)

With so few changes, I wonder if there is a way to re-use the rest of the css instead of duplicating it twice.

**Comment by Geehu** [comment]
That could easily be done by creating a base style-sheet and a color-theme style-sheet. It would require re-arranging the order of the existing style sheet to collect all the colors together. A single style-sheet per theme is simple and straight-forward and maintains the existing layout of the CSS file. Multiple style-sheets eliminates duplication at the cost of being a bit more complex. I didn't know which was preferred. It appears the latter is, so I'll update the code to do that.

**Comment by smichel17** [comment]
@Geehu I'm not an authority on this, I was actually just curious. I'd wait and see what @mpcjanssen thinks.

**Comment by mpcjanssen** [comment]
Thank you. I am not 100% sure of the splitting of isDarkTheme and isBlackTheme, but this works well and is simple.

**Pull request merged**
