### PR TITLE
new debug icon and app name 2

### PR DESCRIPTION
**Pull request by smichel17**

### CODE REVIEW

**Comment by smichel17** [comment]
This is my second choice. I like the gear in concept, but as with the third option, it just doesn't look as good when it's actually an icon on the launcher, imo.

**Comment by smichel17** [comment]
Part of it is execution. I'd need to resize (enlarge) the gear to make it look good, instead of just taking the shape from google's `settings` icon.

**Comment by mpcjanssen** [comment]
This one has my preference too.

**Comment by mpcjanssen** [comment]
Don't spend too much time on this. It's for dev only anyway.

**Pull request merged**
