### PR TITLE
WIP: mostly fixes #599

### LINKED ISSUE #599: Create is threshold should impact Lua scripts
When create is threshold is selected, I believe a tasks .threshold property should be the create date when the threshold date is missing.

### PR DESCRIPTION
**Pull request by smichel17**
Grouping and filtering obeys createIsThreshold. Testing in the filter script fragment still does not obey createIsThreshold

### CODE REVIEW

**Comment by mpcjanssen** [comment]
@smichel17 instead of fixing this by passing the createIsThreshold to the filter callback directly. I would prefer to add a Lua function to get the value of the create is threshold setting so you can decide yourself if you want to obey it in the callback. It can also be more easily extended to other settings which impact the sort.

**Comment by smichel17** [comment]
I would prefer that too but couldn't make getting the active filter work so I just went for the quick and dirty solution.

**Comment by mpcjanssen** [comment]
@smichel17 is this PR still going anywhere or can it be closed?

**Comment by smichel17** [comment]
I will come back to it eventually but not sure exactly when, so I'll close it for now.

**Pull request closed without merging**
